# AUTOGENERATED FILE - DO NOT MODIFY!
set(jni_supportlib_source_files
support-lib/jni/Marshal.hpp
support-lib/jni/djinni_main.cpp
support-lib/jni/djinni_support.cpp
support-lib/jni/djinni_support.hpp
)
