// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <string>
#include <utility>

namespace Kullo { namespace Http {

struct HttpHeader final {
    std::string key;
    std::string value;

    HttpHeader(std::string key,
               std::string value)
    : key(std::move(key))
    , value(std::move(value))
    {}
};

} }  // namespace Kullo::Http
