// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Http {

enum class HttpMethod : int {
    Get,
    Post,
    Put,
    Patch,
    Delete,
};

} }  // namespace Kullo::Http

namespace std {

template <>
struct hash<::Kullo::Http::HttpMethod> {
    size_t operator()(::Kullo::Http::HttpMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
