// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Http {

enum class ProgressResult : int {
    Continue,
    Cancel,
};

} }  // namespace Kullo::Http

namespace std {

template <>
struct hash<::Kullo::Http::ProgressResult> {
    size_t operator()(::Kullo::Http::ProgressResult type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
