// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace Kullo { namespace Http {

class RequestListener {
public:
    virtual ~RequestListener() {}

    virtual std::vector<uint8_t> read(int64_t maxSize) = 0;
};

} }  // namespace Kullo::Http
