// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "kulloclient/http/HttpHeader.h"
#include "kulloclient/http/HttpMethod.h"
#include <string>
#include <utility>
#include <vector>

namespace Kullo { namespace Http {

struct Request final {
    HttpMethod method;
    std::string url;
    std::vector<HttpHeader> headers;

    Request(HttpMethod method,
            std::string url,
            std::vector<HttpHeader> headers)
    : method(std::move(method))
    , url(std::move(url))
    , headers(std::move(headers))
    {}
};

} }  // namespace Kullo::Http
