// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "kulloclient/http/HttpHeader.h"
#include "kulloclient/http/HttpMethod.h"
#include <string>
#include <utility>
#include <vector>

namespace Kullo { namespace Http {

struct Request final {
    HttpMethod method;
    std::string url;
    std::vector<HttpHeader> headers;

    Request(HttpMethod method_,
            std::string url_,
            std::vector<HttpHeader> headers_)
    : method(std::move(method_))
    , url(std::move(url_))
    , headers(std::move(headers_))
    {}
};

} }  // namespace Kullo::Http
