// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "kulloclient/http/HttpHeader.h"
#include "kulloclient/http/ResponseError.h"
#include <boost/optional.hpp>
#include <cstdint>
#include <utility>
#include <vector>

namespace Kullo { namespace Http {

struct Response final {
    boost::optional<ResponseError> error;
    int32_t statusCode;
    std::vector<HttpHeader> headers;

    Response(boost::optional<ResponseError> error_,
             int32_t statusCode_,
             std::vector<HttpHeader> headers_)
    : error(std::move(error_))
    , statusCode(std::move(statusCode_))
    , headers(std::move(headers_))
    {}
};

} }  // namespace Kullo::Http
