// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "kulloclient/http/ProgressResult.h"
#include <cstdint>
#include <vector>

namespace Kullo { namespace Http {

class ResponseListener {
public:
    virtual ~ResponseListener() {}

    /**
     * Returns the progress made on upload and download, measured in bytes. The
     * request can be canceled by returning the appropriate code.
     */
    virtual ProgressResult progress(int64_t uploadTransferred, int64_t uploadTotal, int64_t downloadTransferred, int64_t downloadTotal) = 0;

    virtual void dataReceived(const std::vector<uint8_t> & data) = 0;
};

} }  // namespace Kullo::Http
