// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "kulloclient/http/HttpHeader.h"
#include "kulloclient/http/ResponseError.h"
#include <boost/optional.hpp>
#include <cstdint>
#include <utility>
#include <vector>

namespace Kullo { namespace Http {

struct Response final {
    boost::optional<ResponseError> error;
    int32_t statusCode;
    std::vector<HttpHeader> headers;

    Response(boost::optional<ResponseError> error,
             int32_t statusCode,
             std::vector<HttpHeader> headers)
    : error(std::move(error))
    , statusCode(std::move(statusCode))
    , headers(std::move(headers))
    {}
};

} }  // namespace Kullo::Http
