# AUTOGENERATED FILE - DO NOT MODIFY!
set(http_cpp_source_files
http/HttpClient.h
http/HttpClientFactory.h
http/HttpHeader.h
http/HttpMethod.h
http/ProgressResult.h
http/Registry.h
http/Request.h
http/RequestListener.h
http/Response.h
http/ResponseError.h
http/ResponseListener.h
)
