// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/AddressHelpers.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class AddressHelpers final : ::djinni::JniInterface<::Kullo::Api::AddressHelpers, AddressHelpers> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::AddressHelpers>;
    using CppOptType = std::shared_ptr<::Kullo::Api::AddressHelpers>;
    using JniType = jobject;

    using Boxed = AddressHelpers;

    ~AddressHelpers();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "AddressHelpers::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<AddressHelpers>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<AddressHelpers>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    AddressHelpers();
    friend ::djinni::JniClass<AddressHelpers>;
    friend ::djinni::JniInterface<::Kullo::Api::AddressHelpers, AddressHelpers>;

};

} } }  // namespace JNI::Kullo::Api
