// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api_impl/Address.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class Address final {
public:
    using CppType = ::Kullo::Api::Address;
    using JniType = jobject;

    using Boxed = Address;

    ~Address();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    Address();
    friend ::djinni::JniClass<Address>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/Address") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_localPart { ::djinni::jniGetFieldID(clazz.get(), "localPart", "Ljava/lang/String;") };
    const jfieldID field_domainPart { ::djinni::jniGetFieldID(clazz.get(), "domainPart", "Ljava/lang/String;") };
};

} } }  // namespace JNI::Kullo::Api
