// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from asynctask.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/AsyncTask.h"

namespace JNI { namespace Kullo { namespace Api {

class AsyncTask final : ::djinni::JniInterface<::Kullo::Api::AsyncTask, AsyncTask> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::AsyncTask>;
    using CppOptType = std::shared_ptr<::Kullo::Api::AsyncTask>;
    using JniType = jobject;

    using Boxed = AsyncTask;

    ~AsyncTask();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<AsyncTask>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<AsyncTask>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    AsyncTask();
    friend ::djinni::JniClass<AsyncTask>;
    friend ::djinni::JniInterface<::Kullo::Api::AsyncTask, AsyncTask>;

};

} } }  // namespace JNI::Kullo::Api
