// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/AttachmentsBlockDownloadProgress.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class AttachmentsBlockDownloadProgress final {
public:
    using CppType = ::Kullo::Api::AttachmentsBlockDownloadProgress;
    using JniType = jobject;

    using Boxed = AttachmentsBlockDownloadProgress;

    ~AttachmentsBlockDownloadProgress();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    AttachmentsBlockDownloadProgress();
    friend ::djinni::JniClass<AttachmentsBlockDownloadProgress>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/AttachmentsBlockDownloadProgress") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(JJ)V") };
    const jfieldID field_downloadedBytes { ::djinni::jniGetFieldID(clazz.get(), "downloadedBytes", "J") };
    const jfieldID field_totalBytes { ::djinni::jniGetFieldID(clazz.get(), "totalBytes", "J") };
};

} } }  // namespace JNI::Kullo::Api
