// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/ClientCheckLoginListener.h"

namespace JNI { namespace Kullo { namespace Api {

class ClientCheckLoginListener final : ::djinni::JniInterface<::Kullo::Api::ClientCheckLoginListener, ClientCheckLoginListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::ClientCheckLoginListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::ClientCheckLoginListener>;
    using JniType = jobject;

    using Boxed = ClientCheckLoginListener;

    ~ClientCheckLoginListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<ClientCheckLoginListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ClientCheckLoginListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ClientCheckLoginListener();
    friend ::djinni::JniClass<ClientCheckLoginListener>;
    friend ::djinni::JniInterface<::Kullo::Api::ClientCheckLoginListener, ClientCheckLoginListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::ClientCheckLoginListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(const std::shared_ptr<::Kullo::Api::Address> & address, const std::shared_ptr<::Kullo::Api::MasterKey> & masterKey, bool valid) override;
        void error(const std::shared_ptr<::Kullo::Api::Address> & address, ::Kullo::Api::NetworkError error) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::ClientCheckLoginListener, ::JNI::Kullo::Api::ClientCheckLoginListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/ClientCheckLoginListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(Lnet/kullo/libkullo/api/Address;Lnet/kullo/libkullo/api/MasterKey;Z)V") };
    const jmethodID method_error { ::djinni::jniGetMethodID(clazz.get(), "error", "(Lnet/kullo/libkullo/api/Address;Lnet/kullo/libkullo/api/NetworkError;)V") };
};

} } }  // namespace JNI::Kullo::Api
