// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Client.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class Client final : ::djinni::JniInterface<::Kullo::Api::Client, Client> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Client>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Client>;
    using JniType = jobject;

    using Boxed = Client;

    ~Client();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "Client::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<Client>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Client>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Client();
    friend ::djinni::JniClass<Client>;
    friend ::djinni::JniInterface<::Kullo::Api::Client, Client>;

};

} } }  // namespace JNI::Kullo::Api
