// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "DateTime.h"  // my header
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

DateTime::DateTime() = default;

DateTime::~DateTime() = default;

auto DateTime::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<DateTime>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.year)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.month)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.day)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.hour)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.minute)),
                                                           ::djinni::get(::djinni::I8::fromCpp(jniEnv, c.second)),
                                                           ::djinni::get(::djinni::I16::fromCpp(jniEnv, c.tzOffsetMinutes)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto DateTime::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<DateTime>::get();
    return {::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_year)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_month)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_day)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_hour)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_minute)),
            ::djinni::I8::toCpp(jniEnv, jniEnv->GetByteField(j, data.field_second)),
            ::djinni::I16::toCpp(jniEnv, jniEnv->GetShortField(j, data.field_tzOffsetMinutes))};
}

} } }  // namespace JNI::Kullo::Api
