// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/DeliveryReason.h"

namespace JNI { namespace Kullo { namespace Api {

class DeliveryReason final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::DeliveryReason;
    using JniType = jobject;

    using Boxed = DeliveryReason;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<DeliveryReason>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<DeliveryReason>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    DeliveryReason() : JniEnum("net/kullo/libkullo/api/DeliveryReason") {}
    friend ::djinni::JniClass<DeliveryReason>;
};

} } }  // namespace JNI::Kullo::Api
