// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Delivery.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class Delivery final : ::djinni::JniInterface<::Kullo::Api::Delivery, Delivery> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Delivery>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Delivery>;
    using JniType = jobject;

    using Boxed = Delivery;

    ~Delivery();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "Delivery::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<Delivery>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Delivery>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Delivery();
    friend ::djinni::JniClass<Delivery>;
    friend ::djinni::JniInterface<::Kullo::Api::Delivery, Delivery>;

};

} } }  // namespace JNI::Kullo::Api
