// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/DeliveryState.h"

namespace JNI { namespace Kullo { namespace Api {

class DeliveryState final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::DeliveryState;
    using JniType = jobject;

    using Boxed = DeliveryState;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<DeliveryState>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<DeliveryState>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    DeliveryState() : JniEnum("net/kullo/libkullo/api/DeliveryState") {}
    friend ::djinni::JniClass<DeliveryState>;
};

} } }  // namespace JNI::Kullo::Api
