// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Drafts.h"

namespace JNI { namespace Kullo { namespace Api {

class Drafts final : ::djinni::JniInterface<::Kullo::Api::Drafts, Drafts> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::Drafts>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Drafts>;
    using JniType = jobject;

    using Boxed = Drafts;

    ~Drafts();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Drafts>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Drafts>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Drafts();
    friend ::djinni::JniClass<Drafts>;
    friend ::djinni::JniInterface<::Kullo::Api::Drafts, Drafts>;

};

} } }  // namespace JNI::Kullo::Api
