// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/DraftAttachmentsContentListener.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class DraftAttachmentsContentListener final : ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsContentListener, DraftAttachmentsContentListener> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::DraftAttachmentsContentListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::DraftAttachmentsContentListener>;
    using JniType = jobject;

    using Boxed = DraftAttachmentsContentListener;

    ~DraftAttachmentsContentListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "DraftAttachmentsContentListener::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<DraftAttachmentsContentListener>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<DraftAttachmentsContentListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    DraftAttachmentsContentListener();
    friend ::djinni::JniClass<DraftAttachmentsContentListener>;
    friend ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsContentListener, DraftAttachmentsContentListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::DraftAttachmentsContentListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(int64_t convId, int64_t attId, const std::vector<uint8_t> & content) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsContentListener, ::JNI::Kullo::Api::DraftAttachmentsContentListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/DraftAttachmentsContentListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(JJ[B)V") };
};

} } }  // namespace JNI::Kullo::Api
