// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/DraftState.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class DraftState final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::DraftState;
    using JniType = jobject;

    using Boxed = DraftState;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<DraftState>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<DraftState>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    DraftState() : JniEnum("net/kullo/libkullo/api/DraftState") {}
    friend ::djinni::JniClass<DraftState>;
};

} } }  // namespace JNI::Kullo::Api
