// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/DraftAttachmentsSaveToListener.h"

namespace JNI { namespace Kullo { namespace Api {

class DraftAttachmentsSaveToListener final : ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsSaveToListener, DraftAttachmentsSaveToListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::DraftAttachmentsSaveToListener>;
    using JniType = jobject;

    using Boxed = DraftAttachmentsSaveToListener;

    ~DraftAttachmentsSaveToListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<DraftAttachmentsSaveToListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<DraftAttachmentsSaveToListener>::get()._toJava(jniEnv, c)}; }

private:
    DraftAttachmentsSaveToListener();
    friend ::djinni::JniClass<DraftAttachmentsSaveToListener>;
    friend ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsSaveToListener, DraftAttachmentsSaveToListener>;

    class JavaProxy final : ::djinni::JavaProxyCacheEntry, public ::Kullo::Api::DraftAttachmentsSaveToListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(int64_t convId, int64_t attId, const std::string & path) override;
        void error(int64_t convId, int64_t attId, const std::string & path, ::Kullo::Api::LocalError error) override;

    private:
        using ::djinni::JavaProxyCacheEntry::getGlobalRef;
        friend ::djinni::JniInterface<::Kullo::Api::DraftAttachmentsSaveToListener, ::JNI::Kullo::Api::DraftAttachmentsSaveToListener>;
        friend ::djinni::JavaProxyCache<JavaProxy>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/DraftAttachmentsSaveToListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(JJLjava/lang/String;)V") };
    const jmethodID method_error { ::djinni::jniGetMethodID(clazz.get(), "error", "(JJLjava/lang/String;Lnet/kullo/libkullo/api/LocalError;)V") };
};

} } }  // namespace JNI::Kullo::Api
