// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Drafts.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class Drafts final : ::djinni::JniInterface<::Kullo::Api::Drafts, Drafts> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Drafts>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Drafts>;
    using JniType = jobject;

    using Boxed = Drafts;

    ~Drafts();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "Drafts::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<Drafts>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Drafts>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Drafts();
    friend ::djinni::JniClass<Drafts>;
    friend ::djinni::JniInterface<::Kullo::Api::Drafts, Drafts>;

};

} } }  // namespace JNI::Kullo::Api
