// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/EventType.h"

namespace JNI { namespace Kullo { namespace Api {

class EventType final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::EventType;
    using JniType = jobject;

    using Boxed = EventType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EventType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<EventType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EventType() : JniEnum("net/kullo/libkullo/api/EventType") {}
    friend ::djinni::JniClass<EventType>;
};

} } }  // namespace JNI::Kullo::Api
