// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/InternalAddressUtils.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class InternalAddressUtils final : ::djinni::JniInterface<::Kullo::Api::InternalAddressUtils, InternalAddressUtils> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::InternalAddressUtils>;
    using CppOptType = std::shared_ptr<::Kullo::Api::InternalAddressUtils>;
    using JniType = jobject;

    using Boxed = InternalAddressUtils;

    ~InternalAddressUtils();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "InternalAddressUtils::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<InternalAddressUtils>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<InternalAddressUtils>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    InternalAddressUtils();
    friend ::djinni::JniClass<InternalAddressUtils>;
    friend ::djinni::JniInterface<::Kullo::Api::InternalAddressUtils, InternalAddressUtils>;

};

} } }  // namespace JNI::Kullo::Api
