// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/InternalDateTimeUtils.h"

namespace JNI { namespace Kullo { namespace Api {

class InternalDateTimeUtils final : ::djinni::JniInterface<::Kullo::Api::InternalDateTimeUtils, InternalDateTimeUtils> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::InternalDateTimeUtils>;
    using JniType = jobject;

    using Boxed = InternalDateTimeUtils;

    ~InternalDateTimeUtils();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<InternalDateTimeUtils>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<InternalDateTimeUtils>::get()._toJava(jniEnv, c)}; }

private:
    InternalDateTimeUtils();
    friend ::djinni::JniClass<InternalDateTimeUtils>;
    friend ::djinni::JniInterface<::Kullo::Api::InternalDateTimeUtils, InternalDateTimeUtils>;

};

} } }  // namespace JNI::Kullo::Api
