// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from datetime.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/InternalDateTimeUtils.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class InternalDateTimeUtils final : ::djinni::JniInterface<::Kullo::Api::InternalDateTimeUtils, InternalDateTimeUtils> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::InternalDateTimeUtils>;
    using CppOptType = std::shared_ptr<::Kullo::Api::InternalDateTimeUtils>;
    using JniType = jobject;

    using Boxed = InternalDateTimeUtils;

    ~InternalDateTimeUtils();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "InternalDateTimeUtils::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<InternalDateTimeUtils>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<InternalDateTimeUtils>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    InternalDateTimeUtils();
    friend ::djinni::JniClass<InternalDateTimeUtils>;
    friend ::djinni::JniInterface<::Kullo::Api::InternalDateTimeUtils, InternalDateTimeUtils>;

};

} } }  // namespace JNI::Kullo::Api
