// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/LocalError.h"

namespace JNI { namespace Kullo { namespace Api {

class LocalError final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::LocalError;
    using JniType = jobject;

    using Boxed = LocalError;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<LocalError>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<LocalError>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    LocalError() : JniEnum("net/kullo/libkullo/api/LocalError") {}
    friend ::djinni::JniClass<LocalError>;
};

} } }  // namespace JNI::Kullo::Api
