// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/LogListener.h"

namespace JNI { namespace Kullo { namespace Api {

class LogListener final : ::djinni::JniInterface<::Kullo::Api::LogListener, LogListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::LogListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::LogListener>;
    using JniType = jobject;

    using Boxed = LogListener;

    ~LogListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<LogListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<LogListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    LogListener();
    friend ::djinni::JniClass<LogListener>;
    friend ::djinni::JniInterface<::Kullo::Api::LogListener, LogListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::LogListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void writeLogMessage(const std::string & file, int32_t line, const std::string & function, ::Kullo::Api::LogType type, const std::string & message, const std::string & thread, const std::string & stacktrace) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::LogListener, ::JNI::Kullo::Api::LogListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/LogListener") };
    const jmethodID method_writeLogMessage { ::djinni::jniGetMethodID(clazz.get(), "writeLogMessage", "(Ljava/lang/String;ILjava/lang/String;Lnet/kullo/libkullo/api/LogType;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
};

} } }  // namespace JNI::Kullo::Api
