// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from log.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/LogType.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class LogType final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::LogType;
    using JniType = jobject;

    using Boxed = LogType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<LogType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<LogType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    LogType() : JniEnum("net/kullo/libkullo/api/LogType") {}
    friend ::djinni::JniClass<LogType>;
};

} } }  // namespace JNI::Kullo::Api
