// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api_impl/MasterKey.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class MasterKey final {
public:
    using CppType = ::Kullo::Api::MasterKey;
    using JniType = jobject;

    using Boxed = MasterKey;

    ~MasterKey();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    MasterKey();
    friend ::djinni::JniClass<MasterKey>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/MasterKey") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_blocks { ::djinni::jniGetFieldID(clazz.get(), "blocks", "Ljava/util/ArrayList;") };
};

} } }  // namespace JNI::Kullo::Api
