// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/MessageAttachmentsSaveToListener.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class MessageAttachmentsSaveToListener final : ::djinni::JniInterface<::Kullo::Api::MessageAttachmentsSaveToListener, MessageAttachmentsSaveToListener> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::MessageAttachmentsSaveToListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MessageAttachmentsSaveToListener>;
    using JniType = jobject;

    using Boxed = MessageAttachmentsSaveToListener;

    ~MessageAttachmentsSaveToListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "MessageAttachmentsSaveToListener::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<MessageAttachmentsSaveToListener>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<MessageAttachmentsSaveToListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    MessageAttachmentsSaveToListener();
    friend ::djinni::JniClass<MessageAttachmentsSaveToListener>;
    friend ::djinni::JniInterface<::Kullo::Api::MessageAttachmentsSaveToListener, MessageAttachmentsSaveToListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::MessageAttachmentsSaveToListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(int64_t msgId, int64_t attId, const std::string & path) override;
        void error(int64_t msgId, int64_t attId, const std::string & path, ::Kullo::Api::LocalError error) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::MessageAttachmentsSaveToListener, ::JNI::Kullo::Api::MessageAttachmentsSaveToListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/MessageAttachmentsSaveToListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(JJLjava/lang/String;)V") };
    const jmethodID method_error { ::djinni::jniGetMethodID(clazz.get(), "error", "(JJLjava/lang/String;Lnet/kullo/libkullo/api/LocalError;)V") };
};

} } }  // namespace JNI::Kullo::Api
