// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/MessagesSearchListener.h"

namespace JNI { namespace Kullo { namespace Api {

class MessagesSearchListener final : ::djinni::JniInterface<::Kullo::Api::MessagesSearchListener, MessagesSearchListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::MessagesSearchListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::MessagesSearchListener>;
    using JniType = jobject;

    using Boxed = MessagesSearchListener;

    ~MessagesSearchListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<MessagesSearchListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<MessagesSearchListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    MessagesSearchListener();
    friend ::djinni::JniClass<MessagesSearchListener>;
    friend ::djinni::JniInterface<::Kullo::Api::MessagesSearchListener, MessagesSearchListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::MessagesSearchListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(const std::vector<::Kullo::Api::MessagesSearchResult> & results) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::MessagesSearchListener, ::JNI::Kullo::Api::MessagesSearchListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/MessagesSearchListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(Ljava/util/ArrayList;)V") };
};

} } }  // namespace JNI::Kullo::Api
