// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "MessageAttachmentsSaveToListener.h"  // my header
#include "LocalError.h"
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

MessageAttachmentsSaveToListener::MessageAttachmentsSaveToListener() : ::djinni::JniInterface<::Kullo::Api::MessageAttachmentsSaveToListener, MessageAttachmentsSaveToListener>() {}

MessageAttachmentsSaveToListener::~MessageAttachmentsSaveToListener() = default;

MessageAttachmentsSaveToListener::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

MessageAttachmentsSaveToListener::JavaProxy::~JavaProxy() = default;

void MessageAttachmentsSaveToListener::JavaProxy::finished(int64_t c_msgId, int64_t c_attId, const std::string & c_path) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::MessageAttachmentsSaveToListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_finished,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_msgId)),
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_attId)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_path)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void MessageAttachmentsSaveToListener::JavaProxy::error(int64_t c_msgId, int64_t c_attId, const std::string & c_path, ::Kullo::Api::LocalError c_error) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::MessageAttachmentsSaveToListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_error,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_msgId)),
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_attId)),
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_path)),
                           ::djinni::get(::JNI::Kullo::Api::LocalError::fromCpp(jniEnv, c_error)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
