// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/MessageAttachments.h"

namespace JNI { namespace Kullo { namespace Api {

class MessageAttachments final : ::djinni::JniInterface<::Kullo::Api::MessageAttachments, MessageAttachments> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::MessageAttachments>;
    using JniType = jobject;

    using Boxed = MessageAttachments;

    ~MessageAttachments();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<MessageAttachments>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<MessageAttachments>::get()._toJava(jniEnv, c)}; }

private:
    MessageAttachments();
    friend ::djinni::JniClass<MessageAttachments>;
    friend ::djinni::JniInterface<::Kullo::Api::MessageAttachments, MessageAttachments>;

};

} } }  // namespace JNI::Kullo::Api
