// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#include "MessagesSearchListener.h"  // my header
#include "MessagesSearchResult.h"
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

MessagesSearchListener::MessagesSearchListener() : ::djinni::JniInterface<::Kullo::Api::MessagesSearchListener, MessagesSearchListener>() {}

MessagesSearchListener::~MessagesSearchListener() = default;

MessagesSearchListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

MessagesSearchListener::JavaProxy::~JavaProxy() = default;

void MessagesSearchListener::JavaProxy::finished(const std::vector<::Kullo::Api::MessagesSearchResult> & c_results) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::MessagesSearchListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_finished,
                           ::djinni::get(::djinni::List<::JNI::Kullo::Api::MessagesSearchResult>::fromCpp(jniEnv, c_results)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
