// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/PushTokenType.h"

namespace JNI { namespace Kullo { namespace Api {

class PushTokenType final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::PushTokenType;
    using JniType = jobject;

    using Boxed = PushTokenType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<PushTokenType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<PushTokenType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    PushTokenType() : JniEnum("net/kullo/libkullo/api/PushTokenType") {}
    friend ::djinni::JniClass<PushTokenType>;
};

} } }  // namespace JNI::Kullo::Api
