// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/PushToken.h"

namespace JNI { namespace Kullo { namespace Api {

class PushToken final {
public:
    using CppType = ::Kullo::Api::PushToken;
    using JniType = jobject;

    using Boxed = PushToken;

    ~PushToken();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    PushToken();
    friend ::djinni::JniClass<PushToken>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/PushToken") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lnet/kullo/libkullo/api/PushTokenType;Ljava/lang/String;Lnet/kullo/libkullo/api/PushTokenEnvironment;)V") };
    const jfieldID field_type { ::djinni::jniGetFieldID(clazz.get(), "type", "Lnet/kullo/libkullo/api/PushTokenType;") };
    const jfieldID field_token { ::djinni::jniGetFieldID(clazz.get(), "token", "Ljava/lang/String;") };
    const jfieldID field_environment { ::djinni::jniGetFieldID(clazz.get(), "environment", "Lnet/kullo/libkullo/api/PushTokenEnvironment;") };
};

} } }  // namespace JNI::Kullo::Api
