// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Registration.h"

namespace JNI { namespace Kullo { namespace Api {

class Registration final : ::djinni::JniInterface<::Kullo::Api::Registration, Registration> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::Registration>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Registration>;
    using JniType = jobject;

    using Boxed = Registration;

    ~Registration();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Registration>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Registration>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Registration();
    friend ::djinni::JniClass<Registration>;
    friend ::djinni::JniInterface<::Kullo::Api::Registration, Registration>;

};

} } }  // namespace JNI::Kullo::Api
