// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/SearchPredicateOperator.h"

namespace JNI { namespace Kullo { namespace Api {

class SearchPredicateOperator final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Api::SearchPredicateOperator;
    using JniType = jobject;

    using Boxed = SearchPredicateOperator;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<SearchPredicateOperator>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<SearchPredicateOperator>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    SearchPredicateOperator() : JniEnum("net/kullo/libkullo/api/SearchPredicateOperator") {}
    friend ::djinni::JniClass<SearchPredicateOperator>;
};

} } }  // namespace JNI::Kullo::Api
