// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Senders.h"

namespace JNI { namespace Kullo { namespace Api {

class Senders final : ::djinni::JniInterface<::Kullo::Api::Senders, Senders> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::Senders>;
    using JniType = jobject;

    using Boxed = Senders;

    ~Senders();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Senders>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<Senders>::get()._toJava(jniEnv, c)}; }

private:
    Senders();
    friend ::djinni::JniClass<Senders>;
    friend ::djinni::JniInterface<::Kullo::Api::Senders, Senders>;

};

} } }  // namespace JNI::Kullo::Api
