// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#include "SenderPredicate.h"  // my header
#include "SearchPredicateOperator.h"
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

SenderPredicate::SenderPredicate() = default;

SenderPredicate::~SenderPredicate() = default;

auto SenderPredicate::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<SenderPredicate>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::JNI::Kullo::Api::SearchPredicateOperator::fromCpp(jniEnv, c.predicateOperator)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.senderAddress)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto SenderPredicate::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<SenderPredicate>::get();
    return {::JNI::Kullo::Api::SearchPredicateOperator::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_predicateOperator)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_senderAddress))};
}

} } }  // namespace JNI::Kullo::Api
