// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#include "SessionAccountInfoListener.h"  // my header
#include "AccountInfo.h"
#include "NetworkError.h"

namespace JNI { namespace Kullo { namespace Api {

SessionAccountInfoListener::SessionAccountInfoListener() : ::djinni::JniInterface<::Kullo::Api::SessionAccountInfoListener, SessionAccountInfoListener>() {}

SessionAccountInfoListener::~SessionAccountInfoListener() = default;

SessionAccountInfoListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

SessionAccountInfoListener::JavaProxy::~JavaProxy() = default;

void SessionAccountInfoListener::JavaProxy::finished(const ::Kullo::Api::AccountInfo & c_accountInfo) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SessionAccountInfoListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_finished,
                           ::djinni::get(::JNI::Kullo::Api::AccountInfo::fromCpp(jniEnv, c_accountInfo)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void SessionAccountInfoListener::JavaProxy::error(::Kullo::Api::NetworkError c_error) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SessionAccountInfoListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_error,
                           ::djinni::get(::JNI::Kullo::Api::NetworkError::fromCpp(jniEnv, c_error)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
