// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/SessionAccountInfoListener.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class SessionAccountInfoListener final : ::djinni::JniInterface<::Kullo::Api::SessionAccountInfoListener, SessionAccountInfoListener> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::SessionAccountInfoListener>;
    using CppOptType = std::shared_ptr<::Kullo::Api::SessionAccountInfoListener>;
    using JniType = jobject;

    using Boxed = SessionAccountInfoListener;

    ~SessionAccountInfoListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "SessionAccountInfoListener::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<SessionAccountInfoListener>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<SessionAccountInfoListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    SessionAccountInfoListener();
    friend ::djinni::JniClass<SessionAccountInfoListener>;
    friend ::djinni::JniInterface<::Kullo::Api::SessionAccountInfoListener, SessionAccountInfoListener>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::SessionAccountInfoListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void finished(const ::Kullo::Api::AccountInfo & accountInfo) override;
        void error(::Kullo::Api::NetworkError error) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::SessionAccountInfoListener, ::JNI::Kullo::Api::SessionAccountInfoListener>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/SessionAccountInfoListener") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "(Lnet/kullo/libkullo/api/AccountInfo;)V") };
    const jmethodID method_error { ::djinni::jniGetMethodID(clazz.get(), "error", "(Lnet/kullo/libkullo/api/NetworkError;)V") };
};

} } }  // namespace JNI::Kullo::Api
