// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Session.h"

namespace JNI { namespace Kullo { namespace Api {

class Session final : ::djinni::JniInterface<::Kullo::Api::Session, Session> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::Session>;
    using JniType = jobject;

    using Boxed = Session;

    ~Session();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<Session>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<Session>::get()._toJava(jniEnv, c)}; }

private:
    Session();
    friend ::djinni::JniClass<Session>;
    friend ::djinni::JniInterface<::Kullo::Api::Session, Session>;

};

} } }  // namespace JNI::Kullo::Api
