// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "SessionListener.h"  // my header
#include "InternalEvent.h"

namespace JNI { namespace Kullo { namespace Api {

SessionListener::SessionListener() : ::djinni::JniInterface<::Kullo::Api::SessionListener, SessionListener>() {}

SessionListener::~SessionListener() = default;

SessionListener::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

SessionListener::JavaProxy::~JavaProxy() = default;

void SessionListener::JavaProxy::internalEvent(const std::shared_ptr<::Kullo::Api::InternalEvent> & c_event) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SessionListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_internalEvent,
                           ::djinni::get(::JNI::Kullo::Api::InternalEvent::fromCpp(jniEnv, c_event)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
