// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "SyncerRunListener.h"  // my header
#include "NetworkError.h"
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

SyncerRunListener::SyncerRunListener() : ::djinni::JniInterface<::Kullo::Api::SyncerRunListener, SyncerRunListener>() {}

SyncerRunListener::~SyncerRunListener() = default;

SyncerRunListener::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

SyncerRunListener::JavaProxy::~JavaProxy() = default;

void SyncerRunListener::JavaProxy::draftAttachmentsTooBig(int64_t c_convId) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SyncerRunListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_draftAttachmentsTooBig,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_convId)));
    ::djinni::jniExceptionCheck(jniEnv);
}
void SyncerRunListener::JavaProxy::finished() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SyncerRunListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_finished);
    ::djinni::jniExceptionCheck(jniEnv);
}
void SyncerRunListener::JavaProxy::error(::Kullo::Api::NetworkError c_error) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::SyncerRunListener>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_error,
                           ::djinni::get(::JNI::Kullo::Api::NetworkError::fromCpp(jniEnv, c_error)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
