// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/SyncerListener.h"

namespace JNI { namespace Kullo { namespace Api {

class SyncerListener final : ::djinni::JniInterface<::Kullo::Api::SyncerListener, SyncerListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::SyncerListener>;
    using JniType = jobject;

    using Boxed = SyncerListener;

    ~SyncerListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<SyncerListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<SyncerListener>::get()._toJava(jniEnv, c)}; }

private:
    SyncerListener();
    friend ::djinni::JniClass<SyncerListener>;
    friend ::djinni::JniInterface<::Kullo::Api::SyncerListener, SyncerListener>;

    class JavaProxy final : ::djinni::JavaProxyCacheEntry, public ::Kullo::Api::SyncerListener
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void draftAttachmentsTooBig(int64_t convId) override;
        void progressed(const ::Kullo::Api::SyncProgress & progress) override;
        void finished() override;
        void error(::Kullo::Api::NetworkError error) override;

    private:
        using ::djinni::JavaProxyCacheEntry::getGlobalRef;
        friend ::djinni::JniInterface<::Kullo::Api::SyncerListener, ::JNI::Kullo::Api::SyncerListener>;
        friend ::djinni::JavaProxyCache<JavaProxy>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/SyncerListener") };
    const jmethodID method_draftAttachmentsTooBig { ::djinni::jniGetMethodID(clazz.get(), "draftAttachmentsTooBig", "(J)V") };
    const jmethodID method_progressed { ::djinni::jniGetMethodID(clazz.get(), "progressed", "(Lnet/kullo/libkullo/api/SyncProgress;)V") };
    const jmethodID method_finished { ::djinni::jniGetMethodID(clazz.get(), "finished", "()V") };
    const jmethodID method_error { ::djinni::jniGetMethodID(clazz.get(), "error", "(Lnet/kullo/libkullo/api/NetworkError;)V") };
};

} } }  // namespace JNI::Kullo::Api
