// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#include "SyncProgress.h"  // my header
#include "SyncPhase.h"
#include "jni/support-lib/jni/Marshal.hpp"

namespace JNI { namespace Kullo { namespace Api {

SyncProgress::SyncProgress() = default;

SyncProgress::~SyncProgress() = default;

auto SyncProgress::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<SyncProgress>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::JNI::Kullo::Api::SyncPhase::fromCpp(jniEnv, c.phase)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesProcessed)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesTotal)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesNew)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesNewUnread)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesModified)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingMessagesDeleted)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingAttachmentsDownloadedBytes)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.incomingAttachmentsTotalBytes)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.outgoingMessagesUploadedBytes)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.outgoingMessagesTotalBytes)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.runTimeMs)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto SyncProgress::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 13);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<SyncProgress>::get();
    return {::JNI::Kullo::Api::SyncPhase::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_phase)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesProcessed)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesTotal)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesNew)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesNewUnread)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesModified)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingMessagesDeleted)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingAttachmentsDownloadedBytes)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_incomingAttachmentsTotalBytes)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_outgoingMessagesUploadedBytes)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_outgoingMessagesTotalBytes)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_runTimeMs))};
}

} } }  // namespace JNI::Kullo::Api
