// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/Syncer.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Api {

class Syncer final : ::djinni::JniInterface<::Kullo::Api::Syncer, Syncer> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Api::Syncer>;
    using CppOptType = std::shared_ptr<::Kullo::Api::Syncer>;
    using JniType = jobject;

    using Boxed = Syncer;

    ~Syncer();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "Syncer::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<Syncer>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<Syncer>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    Syncer();
    friend ::djinni::JniClass<Syncer>;
    friend ::djinni::JniInterface<::Kullo::Api::Syncer, Syncer>;

};

} } }  // namespace JNI::Kullo::Api
