// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "TaskRunner.h"  // my header
#include "Task.h"

namespace JNI { namespace Kullo { namespace Api {

TaskRunner::TaskRunner() : ::djinni::JniInterface<::Kullo::Api::TaskRunner, TaskRunner>() {}

TaskRunner::~TaskRunner() = default;

TaskRunner::JavaProxy::JavaProxy(JniType j) : JavaProxyCacheEntry(j) { }

TaskRunner::JavaProxy::~JavaProxy() = default;

void TaskRunner::JavaProxy::runTaskAsync(const std::shared_ptr<::Kullo::Api::Task> & c_task) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::JNI::Kullo::Api::TaskRunner>::get();
    jniEnv->CallVoidMethod(getGlobalRef(), data.method_runTaskAsync,
                           ::djinni::get(::JNI::Kullo::Api::Task::fromCpp(jniEnv, c_task)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} } }  // namespace JNI::Kullo::Api
