// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from taskrunner.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/api/TaskRunner.h"

namespace JNI { namespace Kullo { namespace Api {

class TaskRunner final : ::djinni::JniInterface<::Kullo::Api::TaskRunner, TaskRunner> {
public:
    using CppType = std::shared_ptr<::Kullo::Api::TaskRunner>;
    using CppOptType = std::shared_ptr<::Kullo::Api::TaskRunner>;
    using JniType = jobject;

    using Boxed = TaskRunner;

    ~TaskRunner();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<TaskRunner>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<TaskRunner>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    TaskRunner();
    friend ::djinni::JniClass<TaskRunner>;
    friend ::djinni::JniInterface<::Kullo::Api::TaskRunner, TaskRunner>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::Kullo::Api::TaskRunner
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void runTaskAsync(const std::shared_ptr<::Kullo::Api::Task> & task) override;

    private:
        friend ::djinni::JniInterface<::Kullo::Api::TaskRunner, ::JNI::Kullo::Api::TaskRunner>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("net/kullo/libkullo/api/TaskRunner") };
    const jmethodID method_runTaskAsync { ::djinni::jniGetMethodID(clazz.get(), "runTaskAsync", "(Lnet/kullo/libkullo/api/Task;)V") };
};

} } }  // namespace JNI::Kullo::Api
