// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#pragma once

#include <string>
#include <utility>

namespace Kullo { namespace Api {

/** Information about a Kullo account */
struct AccountInfo final {
    /**
     * URL to web interface where account settings (notifications, ...) can be
     * configured
     */
    std::string settingsUrl;

    AccountInfo(std::string settingsUrl_)
    : settingsUrl(std::move(settingsUrl_))
    {}
};

} }  // namespace Kullo::Api
