// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#pragma once

#include <boost/optional.hpp>
#include <string>

namespace Kullo { namespace Api {

struct Address;

class AddressHelpers {
public:
    virtual ~AddressHelpers() {}

    static boost::optional<Address> create(const std::string & address);
};

} }  // namespace Kullo::Api
