// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <memory>

namespace Kullo { namespace Api {

class Address;
class MasterKey;
enum class NetworkError;

/** Listener used in Client.checkLoginAsync() */
class ClientCheckLoginListener {
public:
    virtual ~ClientCheckLoginListener() {}

    virtual void finished(const std::shared_ptr<Address> & address, const std::shared_ptr<MasterKey> & masterKey, bool valid) = 0;

    virtual void error(const std::shared_ptr<Address> & address, NetworkError error) = 0;
};

} }  // namespace Kullo::Api
