// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

#include <memory>

namespace Kullo { namespace Api {

class Address;
enum class NetworkError;

/** Listener used in Client.addressExistsAsync() */
class ClientAddressExistsListener {
public:
    virtual ~ClientAddressExistsListener() {}

    virtual void finished(const std::shared_ptr<Address> & address, bool exists) = 0;

    virtual void error(const std::shared_ptr<Address> & address, NetworkError error) = 0;
};

} }  // namespace Kullo::Api
