// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client.djinni

#pragma once

namespace Kullo { namespace Api {

enum class NetworkError;
struct Address;
struct MasterKey;

/** Listener used in Client.checkCredentialsAsync() */
class ClientCheckCredentialsListener {
public:
    virtual ~ClientCheckCredentialsListener() {}

    virtual void finished(const Address & address, const MasterKey & masterKey, bool valid) = 0;

    /**
     * Network errors except NetworkError.Unauthorized, which is handled
     * by finished()
     */
    virtual void error(const Address & address, NetworkError error) = 0;
};

} }  // namespace Kullo::Api
