// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#include "kulloclient/api/Client.h"  // my header

namespace Kullo { namespace Api {

std::string const Client::BOTAN = {"Botan"};

std::string const Client::BOOST = {"Boost"};

std::string const Client::JSONCPP = {"JsonCpp"};

std::string const Client::LIBKULLO = {"libkullo"};

std::string const Client::SMARTSQLITE = {"SmartSqlite"};

std::string const Client::SQLITE = {"SQLite"};

} }  // namespace Kullo::Api
