// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <boost/optional.hpp>

namespace Kullo { namespace Api {

enum class DeliveryReason;
enum class DeliveryState;
struct Address;
struct DateTime;

/** Delivery information for a single recipient. */
class Delivery {
public:
    virtual ~Delivery() {}

    virtual Address recipient() = 0;

    virtual DeliveryState state() = 0;

    virtual boost::optional<DeliveryReason> reason() = 0;

    virtual boost::optional<DateTime> date() = 0;
};

} }  // namespace Kullo::Api
