// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class DeliveryReason : int {
    Unknown,
    DoesntExist,
    TooLarge,
    Canceled,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::DeliveryReason> {
    size_t operator()(::Kullo::Api::DeliveryReason type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
