// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <boost/optional.hpp>
#include <memory>

namespace Kullo { namespace Api {

class Address;
enum class DeliveryReason;
enum class DeliveryState;
struct DateTime;

/** Delivery information for a single recipient. */
class Delivery {
public:
    virtual ~Delivery() {}

    virtual std::shared_ptr<Address> recipient() = 0;

    virtual DeliveryState state() = 0;

    virtual boost::optional<DeliveryReason> reason() = 0;

    virtual boost::optional<DateTime> date() = 0;
};

} }  // namespace Kullo::Api
