// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class DeliveryState : int {
    Unsent,
    Delivered,
    Failed,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::DeliveryState> {
    size_t operator()(::Kullo::Api::DeliveryState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
