// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/DraftState.h"
#include <cstdint>
#include <string>

namespace Kullo { namespace Api {

class Drafts {
public:
    virtual ~Drafts() {}

    virtual std::string text(int64_t convId) = 0;

    virtual void setText(int64_t convId, const std::string & text) = 0;

    virtual DraftState state(int64_t convId) = 0;

    /**
     * The draft will be sent on the next sync. This will throw an exception if
     * UserSettings::name() is empty.
     */
    virtual void prepareToSend(int64_t convId) = 0;

    /** Clears the draft and removes the corresponding attachments. */
    virtual void clear(int64_t convId) = 0;
};

} }  // namespace Kullo::Api
