// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class DraftState : int {
    Editing,
    Sending,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::DraftState> {
    size_t operator()(::Kullo::Api::DraftState type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
