// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace Kullo { namespace Api {

/** Listener used in DraftAttachments.contentAsync() */
class DraftAttachmentsContentListener {
public:
    virtual ~DraftAttachmentsContentListener() {}

    virtual void finished(int64_t convId, int64_t attId, const std::vector<uint8_t> & content) = 0;
};

} }  // namespace Kullo::Api
