// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/LocalError.h"
#include <cstdint>
#include <string>

namespace Kullo { namespace Api {

/** Listener used in DraftAttachments.saveToAsync() */
class DraftAttachmentsSaveToListener {
public:
    virtual ~DraftAttachmentsSaveToListener() {}

    virtual void finished(int64_t convId, int64_t attId, const std::string & path) = 0;

    virtual void error(int64_t convId, int64_t attId, const std::string & path, LocalError error) = 0;
};

} }  // namespace Kullo::Api
