// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from drafts.djinni

#pragma once

#include <cstdint>
#include <string>

namespace Kullo { namespace Api {

enum class LocalError;

/** Listener used in DraftAttachments.addAsync() */
class DraftAttachmentsAddListener {
public:
    virtual ~DraftAttachmentsAddListener() {}

    /**
     * Indicates progress when adding an attachment.
     * Note: not guaranteed to be called at any specific point.
     */
    virtual void progressed(int64_t convId, int64_t attId, int64_t bytesProcessed, int64_t bytesTotal) = 0;

    virtual void finished(int64_t convId, int64_t attId, const std::string & path) = 0;

    virtual void error(int64_t convId, const std::string & path, LocalError error) = 0;
};

} }  // namespace Kullo::Api
