// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/EventType.h"
#include <cstdint>
#include <utility>

namespace Kullo { namespace Api {

struct Event final {
    EventType event;
    /** -1 if not applicable */
    int64_t conversationId;
    /** -1 if not applicable */
    int64_t messageId;
    /** -1 if not applicable */
    int64_t attachmentId;

    Event(EventType event,
          int64_t conversationId,
          int64_t messageId,
          int64_t attachmentId)
    : event(std::move(event))
    , conversationId(std::move(conversationId))
    , messageId(std::move(messageId))
    , attachmentId(std::move(attachmentId))
    {}
};

} }  // namespace Kullo::Api
