// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

namespace Kullo { namespace Api {

/**
 * Intentionally empty interface, because it cannot be used outside of C++,
 * other than being passed along to Session.notify().
 */
class InternalEvent {
public:
    virtual ~InternalEvent() {}
};

} }  // namespace Kullo::Api
