// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from masterkey.djinni

#pragma once

#include <string>
#include <vector>

namespace Kullo { namespace Api {

class InternalMasterKeyUtils {
public:
    virtual ~InternalMasterKeyUtils() {}

    /** Checks a MasterKey constructor argument for validity */
    static bool isValid(const std::vector<std::string> & blocks);
};

} }  // namespace Kullo::Api
