// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from address.djinni

#pragma once

#include <string>

namespace Kullo { namespace Api {

class InternalAddressUtils {
public:
    virtual ~InternalAddressUtils() {}

    /** Checks a set of Address constructor arguments for validity */
    static bool isValid(const std::string & localPart, const std::string & domainPart);
};

} }  // namespace Kullo::Api
