// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from errors.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class LocalError : int {
    /** Couldn't read or write to file */
    Filesystem,
    /** Any other error */
    Unknown,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::LocalError> {
    size_t operator()(::Kullo::Api::LocalError type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
