// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/LogType.h"
#include <cstdint>
#include <string>

namespace Kullo { namespace Api {

/** Listener used in Registry.setLogListener() */
class LogListener {
public:
    virtual ~LogListener() {}

    /** Called whenever libkullo produces a log message. */
    virtual void writeLogMessage(const std::string & file, int32_t line, const std::string & function, LogType type, const std::string & message, const std::string & thread, const std::string & stacktrace) = 0;
};

} }  // namespace Kullo::Api
