// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <vector>

namespace Kullo { namespace Api {

struct MessagesSearchResult;

class MessagesSearchListener {
public:
    virtual ~MessagesSearchListener() {}

    virtual void finished(const std::vector<MessagesSearchResult> & results) = 0;
};

} }  // namespace Kullo::Api
