// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace Kullo { namespace Api {

/** Listener used in MessageAttachments.contentAsync() */
class MessageAttachmentsContentListener {
public:
    virtual ~MessageAttachmentsContentListener() {}

    virtual void finished(int64_t msgId, int64_t attId, const std::vector<uint8_t> & content) = 0;
};

} }  // namespace Kullo::Api
