// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <cstdint>
#include <string>

namespace Kullo { namespace Api {

enum class LocalError;

/** Listener used in MessageAttachments.saveToAsync() */
class MessageAttachmentsSaveToListener {
public:
    virtual ~MessageAttachmentsSaveToListener() {}

    virtual void finished(int64_t msgId, int64_t attId, const std::string & path) = 0;

    virtual void error(int64_t msgId, int64_t attId, const std::string & path, LocalError error) = 0;
};

} }  // namespace Kullo::Api
