// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "kulloclient/api_impl/DateTime.h"
#include <cstdint>
#include <string>
#include <utility>

namespace Kullo { namespace Api {

struct MessagesSearchResult final {
    int64_t msgId;
    int64_t convId;
    std::string senderAddress;
    DateTime dateReceived;
    /**
     * Snippet contains search strings wrapped in "(XYZ)" and "(/XYZ)" where XYZ
     * is a random boundary in the format [a-zA-Z0-9]+ generated in every search
     */
    std::string snippet;
    std::string boundary;

    MessagesSearchResult(int64_t msgId_,
                         int64_t convId_,
                         std::string senderAddress_,
                         DateTime dateReceived_,
                         std::string snippet_,
                         std::string boundary_)
    : msgId(std::move(msgId_))
    , convId(std::move(convId_))
    , senderAddress(std::move(senderAddress_))
    , dateReceived(std::move(dateReceived_))
    , snippet(std::move(snippet_))
    , boundary(std::move(boundary_))
    {}
};

} }  // namespace Kullo::Api
