// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class PushTokenType : int {
    /** Google Cloud Messaging */
    GCM,
    /** Apple Push Notification Service */
    APNS,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::PushTokenType> {
    size_t operator()(::Kullo::Api::PushTokenType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
