// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from push.djinni

#pragma once

#include "kulloclient/api/PushTokenEnvironment.h"
#include "kulloclient/api/PushTokenType.h"
#include <string>
#include <utility>

namespace Kullo { namespace Api {

struct PushToken final {
    PushTokenType type;
    /** GCM: the token; APNS: the hex-encoded token */
    std::string token;
    PushTokenEnvironment environment;

    PushToken(PushTokenType type_,
              std::string token_,
              PushTokenEnvironment environment_)
    : type(std::move(type_))
    , token(std::move(token_))
    , environment(std::move(environment_))
    {}
};

} }  // namespace Kullo::Api
