// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registration.djinni

#pragma once

#include <kulloclient/nn.h>
#include <memory>

namespace Kullo { namespace Api {

class Challenge;
enum class AddressNotAvailableReason;
enum class NetworkError;
struct Address;
struct MasterKey;

/** Listener used in Registration.registerAccountAsync() */
class RegistrationRegisterAccountListener {
public:
    virtual ~RegistrationRegisterAccountListener() {}

    virtual void challengeNeeded(const Address & address, const ::Kullo::nn_shared_ptr<Challenge> & challenge) = 0;

    virtual void addressNotAvailable(const Address & address, AddressNotAvailableReason reason) = 0;

    virtual void finished(const Address & address, const MasterKey & masterKey) = 0;

    virtual void error(const Address & address, NetworkError error) = 0;
};

} }  // namespace Kullo::Api
