// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from registry.djinni

#pragma once

#include <boost/optional.hpp>
#include <memory>

namespace Kullo { namespace Api {

class LogListener;
class TaskRunner;

/** Registry for helpers that are used by libkullo. */
class Registry {
public:
    virtual ~Registry() {}

    /**
     * Sets the log listener. If null is passed, default behavior is restored,
     * which means writing the log messages to stdout.
     */
    static void setLogListener(const std::shared_ptr<LogListener> & listener);

    /** Sets a new TaskRunner. Must be done before any async method is called. */
    static void setTaskRunner(const std::shared_ptr<TaskRunner> & taskRunner);
};

} }  // namespace Kullo::Api
