// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include "kulloclient/api/SearchPredicateOperator.h"
#include <string>
#include <utility>

namespace Kullo { namespace Api {

struct SenderPredicate final {
    SearchPredicateOperator predicateOperator;
    std::string senderAddress;

    SenderPredicate(SearchPredicateOperator predicateOperator_,
                    std::string senderAddress_)
    : predicateOperator(std::move(predicateOperator_))
    , senderAddress(std::move(senderAddress_))
    {}
};

} }  // namespace Kullo::Api
