// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from messages.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace Kullo { namespace Api {

class Address;

class Senders {
public:
    virtual ~Senders() {}

    virtual std::string name(int64_t msgId) = 0;

    virtual std::shared_ptr<Address> address(int64_t msgId) = 0;

    virtual std::string organization(int64_t msgId) = 0;

    virtual std::string avatarMimeType(int64_t msgId) = 0;

    virtual std::vector<uint8_t> avatar(int64_t msgId) = 0;
};

} }  // namespace Kullo::Api
