// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <memory>

namespace Kullo { namespace Api {

class InternalEvent;

/** Listener used in Client.createSessionAsync() */
class SessionListener {
public:
    virtual ~SessionListener() {}

    /** event must be passed to Session.notify() from UI thread */
    virtual void internalEvent(const std::shared_ptr<InternalEvent> & event) = 0;
};

} }  // namespace Kullo::Api
