// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from session.djinni

#pragma once

namespace Kullo { namespace Api {

enum class NetworkError;
struct AccountInfo;

/** Listener used in Session.accountInfoAsync() */
class SessionAccountInfoListener {
public:
    virtual ~SessionAccountInfoListener() {}

    virtual void finished(const AccountInfo & accountInfo) = 0;

    virtual void error(NetworkError error) = 0;
};

} }  // namespace Kullo::Api
