// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/Event.h"
#include <memory>
#include <vector>

namespace Kullo { namespace Api {

class AsyncTask;
class Conversations;
class DraftAttachments;
class Drafts;
class InternalEvent;
class MessageAttachments;
class Messages;
class Senders;
class SessionAccountInfoListener;
class Syncer;
class UserSettings;

class Session {
public:
    virtual ~Session() {}

    virtual std::shared_ptr<UserSettings> userSettings() = 0;

    virtual std::shared_ptr<Conversations> conversations() = 0;

    virtual std::shared_ptr<Messages> messages() = 0;

    virtual std::shared_ptr<MessageAttachments> messageAttachments() = 0;

    virtual std::shared_ptr<Senders> senders() = 0;

    virtual std::shared_ptr<Drafts> drafts() = 0;

    virtual std::shared_ptr<DraftAttachments> draftAttachments() = 0;

    virtual std::shared_ptr<Syncer> syncer() = 0;

    virtual std::shared_ptr<AsyncTask> accountInfoAsync(const std::shared_ptr<SessionAccountInfoListener> & listener) = 0;

    /** Notify the session of events. Only call this from the UI thread! */
    virtual std::vector<Event> notify(const std::shared_ptr<InternalEvent> & internalEvent) = 0;
};

} }  // namespace Kullo::Api
