// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class SyncMode : int {
    /** Do the minimal work required to send all unsent prepared drafts */
    SendOnly,
    /** Sync everything, but don't download attachments */
    WithoutAttachments,
    /** Sync everything, including attachments */
    Everything,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::SyncMode> {
    size_t operator()(::Kullo::Api::SyncMode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
