// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/SyncMode.h"
#include <cstdint>
#include <memory>

namespace Kullo { namespace Api {

class AsyncTask;
class SyncerRunListener;

class Syncer {
public:
    virtual ~Syncer() {}

    /** Synchronize messages etc. with the server. */
    virtual std::shared_ptr<AsyncTask> runAsync(SyncMode mode, const std::shared_ptr<SyncerRunListener> & listener) = 0;

    /** Download all attachments for a given message */
    virtual std::shared_ptr<AsyncTask> downloadAttachmentsForMessageAsync(int64_t msgId, const std::shared_ptr<SyncerRunListener> & listener) = 0;
};

} }  // namespace Kullo::Api
