// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#pragma once

#include <functional>

namespace Kullo { namespace Api {

enum class SyncPhase : int {
    Keys,
    Profile,
    /** Downloading and processing of incoming messages */
    IncomingMessages,
    /** Downloading and processing of attachments */
    IncomingAttachments,
    /** Sending messages */
    OutgoingMessages,
};

} }  // namespace Kullo::Api

namespace std {

template <>
struct hash<::Kullo::Api::SyncPhase> {
    size_t operator()(::Kullo::Api::SyncPhase type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
