// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#pragma once

#include <cstdint>
#include <memory>

namespace Kullo { namespace Api {

class SyncerListener;
enum class SyncMode;

/**
 * Handles syncing, including downloading of attachments. Prevents multiple syncs
 * from running in parallel by building a queue and intelligently merging sync
 * requests.
 * Examples: Enqueuing a WithoutAttachments sync removes a SendOnly sync from the
 * queue. A running SendOnly sync would be cancelled. Enqueuing a SendOnly sync
 * while a WithoutAttachments sync is running or enqueued will do nothing.
 * Enqueuing an Everything sync will remove all attachment download requests from
 * the queue.
 */
class Syncer {
public:
    virtual ~Syncer() {}

    /** Set or replace the SyncerListener which should receive sync events. */
    virtual void setListener(const std::shared_ptr<SyncerListener> & listener) = 0;

    /** Request that the data specified in mode is synced. */
    virtual void requestSync(SyncMode mode) = 0;

    /** Request that all attachments for the given message are downloaded. */
    virtual void requestDownloadingAttachmentsForMessage(int64_t msgId) = 0;

    /**
     * Cancels the running sync and enqueued syncs, but doesn't wait for
     * termination. Stops all callbacks, even if the task continues to run.
     */
    virtual void cancel() = 0;

    /** Returns true iff a sync is currently running. */
    virtual bool isSyncing() = 0;

    /** Blocks until the running sync and all enqueued syncs have finished. */
    virtual void waitUntilDone() = 0;

    /**
     * Blocks until the sync and all enqueued syncs have finished executing or
     * until the timeout has expired. Returns false on timeout, true otherwise.
     */
    virtual bool waitForMs(int32_t timeout) = 0;
};

} }  // namespace Kullo::Api
