// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/NetworkError.h"
#include "kulloclient/api/SyncProgress.h"
#include <cstdint>

namespace Kullo { namespace Api {

/** Listener used in Syncer */
class SyncerListener {
public:
    virtual ~SyncerListener() {}

    /**
     * Called when the attachments of a draft that should be sent are too big.
     * The syncer will continue syncing the other requested items.
     */
    virtual void draftAttachmentsTooBig(int64_t convId) = 0;

    /** Called to inform about the progress of the current sync */
    virtual void progressed(const SyncProgress & progress) = 0;

    /**
     * Called when all requested syncs have finished. Not called when error() is
     * called.
     */
    virtual void finished() = 0;

    /**
     * Called when an error occurred during syncing which makes continuing the
     * sync impossible.
     */
    virtual void error(NetworkError error) = 0;
};

} }  // namespace Kullo::Api
