// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from syncer.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace Kullo { namespace Api {

struct SyncProgress final {
    /** stats about messages */
    int64_t countLeft;
    int64_t countProcessed;
    int64_t countTotal;
    int64_t countNew;
    int64_t countNewUnread;
    int64_t countModified;
    int64_t countDeleted;
    /** Run time of the current sync in milliseconds */
    int64_t runTimeMs;

    SyncProgress(int64_t countLeft_,
                 int64_t countProcessed_,
                 int64_t countTotal_,
                 int64_t countNew_,
                 int64_t countNewUnread_,
                 int64_t countModified_,
                 int64_t countDeleted_,
                 int64_t runTimeMs_)
    : countLeft(std::move(countLeft_))
    , countProcessed(std::move(countProcessed_))
    , countTotal(std::move(countTotal_))
    , countNew(std::move(countNew_))
    , countNewUnread(std::move(countNewUnread_))
    , countModified(std::move(countModified_))
    , countDeleted(std::move(countDeleted_))
    , runTimeMs(std::move(runTimeMs_))
    {}
};

} }  // namespace Kullo::Api
