// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from api.djinni

#pragma once

#include "kulloclient/api/NetworkError.h"
#include <cstdint>

namespace Kullo { namespace Api {

/** Listener used in Syncer.runAsync() */
class SyncerRunListener {
public:
    virtual ~SyncerRunListener() {}

    virtual void draftAttachmentsTooBig(int64_t convId) = 0;

    virtual void finished() = 0;

    virtual void error(NetworkError error) = 0;
};

} }  // namespace Kullo::Api
