// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/http/HttpMethod.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Http {

class HttpMethod final : ::djinni::JniEnum {
public:
    using CppType = ::Kullo::Http::HttpMethod;
    using JniType = jobject;

    using Boxed = HttpMethod;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<HttpMethod>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<HttpMethod>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    HttpMethod() : JniEnum("net/kullo/libkullo/http/HttpMethod") {}
    friend ::djinni::JniClass<HttpMethod>;
};

} } }  // namespace JNI::Kullo::Http
