// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/http/RequestListener.h"

namespace JNI { namespace Kullo { namespace Http {

class RequestListener final : ::djinni::JniInterface<::Kullo::Http::RequestListener, RequestListener> {
public:
    using CppType = std::shared_ptr<::Kullo::Http::RequestListener>;
    using JniType = jobject;

    using Boxed = RequestListener;

    ~RequestListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<RequestListener>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return {jniEnv, ::djinni::JniClass<RequestListener>::get()._toJava(jniEnv, c)}; }

private:
    RequestListener();
    friend ::djinni::JniClass<RequestListener>;
    friend ::djinni::JniInterface<::Kullo::Http::RequestListener, RequestListener>;

};

} } }  // namespace JNI::Kullo::Http
