// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/http/RequestListener.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Http {

class RequestListener final : ::djinni::JniInterface<::Kullo::Http::RequestListener, RequestListener> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Http::RequestListener>;
    using CppOptType = std::shared_ptr<::Kullo::Http::RequestListener>;
    using JniType = jobject;

    using Boxed = RequestListener;

    ~RequestListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "RequestListener::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<RequestListener>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<RequestListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    RequestListener();
    friend ::djinni::JniClass<RequestListener>;
    friend ::djinni::JniInterface<::Kullo::Http::RequestListener, RequestListener>;

};

} } }  // namespace JNI::Kullo::Http
