// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from http.djinni

#pragma once

#include "jni/support-lib/jni/djinni_support.hpp"
#include "kulloclient/http/ResponseListener.h"
#include <kulloclient/nn.h>

namespace JNI { namespace Kullo { namespace Http {

class ResponseListener final : ::djinni::JniInterface<::Kullo::Http::ResponseListener, ResponseListener> {
public:
    using CppType = ::Kullo::nn_shared_ptr<::Kullo::Http::ResponseListener>;
    using CppOptType = std::shared_ptr<::Kullo::Http::ResponseListener>;
    using JniType = jobject;

    using Boxed = ResponseListener;

    ~ResponseListener();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) {
        DJINNI_ASSERT_MSG(j, jniEnv, "ResponseListener::fromCpp requires a non-null Java object");
        return kulloForcedNn(::djinni::JniClass<ResponseListener>::get()._fromJava(jniEnv, j));
    };
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<ResponseListener>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    ResponseListener();
    friend ::djinni::JniClass<ResponseListener>;
    friend ::djinni::JniInterface<::Kullo::Http::ResponseListener, ResponseListener>;

};

} } }  // namespace JNI::Kullo::Http
